/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevni.gui;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import sanjeevni.dao.UserDao;
import sanjeevni.dbutil.DBconnection;
import sanjeevni.pojo.User;
import sanjeevni.pojo.UserProfile;
/**
 *
 * @author Admin
 */
public class ManageReceptionistFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageReceptionistFrame
     */
    public ManageReceptionistFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
        Image img=tk.getImage("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Sanjeevni App\\src\\sanjeevni\\icons\\doctor.png");
        this.setIconImage(img);
        if(UserProfile.getUserName()!=null){
            lblName.setText("HELLO,USER-"+UserProfile.getUserName().toUpperCase());
        }
        else{
            lblName.setText("Hello,User!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddReceptionist = new javax.swing.JLabel();
        lblUpdateReceptionist = new javax.swing.JLabel();
        lblViewReceptionist = new javax.swing.JLabel();
        lblRemoveReceptionist = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel10.setText("Sanjeevni Application");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/icons/HomePageBG1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/icons/doctor.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 190, 160));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manager Receptionist");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 40));

        lblLogout.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 410, 70, 20));

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Hello, User-");
        lblName.setOpaque(true);
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 570, 40));

        lblAddReceptionist.setBackground(new java.awt.Color(0, 204, 204));
        lblAddReceptionist.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAddReceptionist.setForeground(new java.awt.Color(255, 255, 255));
        lblAddReceptionist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddReceptionist.setText("Add Receptionist");
        lblAddReceptionist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAddReceptionist.setOpaque(true);
        lblAddReceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddReceptionistMouseClicked(evt);
            }
        });
        getContentPane().add(lblAddReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 220, 40));

        lblUpdateReceptionist.setBackground(new java.awt.Color(0, 204, 204));
        lblUpdateReceptionist.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblUpdateReceptionist.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateReceptionist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateReceptionist.setText("Update Receptionist");
        lblUpdateReceptionist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblUpdateReceptionist.setOpaque(true);
        lblUpdateReceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateReceptionistMouseClicked(evt);
            }
        });
        getContentPane().add(lblUpdateReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 220, 40));

        lblViewReceptionist.setBackground(new java.awt.Color(0, 204, 204));
        lblViewReceptionist.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblViewReceptionist.setForeground(new java.awt.Color(255, 255, 255));
        lblViewReceptionist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewReceptionist.setText("View Receptionist");
        lblViewReceptionist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblViewReceptionist.setOpaque(true);
        lblViewReceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewReceptionistMouseClicked(evt);
            }
        });
        getContentPane().add(lblViewReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 220, 40));

        lblRemoveReceptionist.setBackground(new java.awt.Color(0, 204, 204));
        lblRemoveReceptionist.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblRemoveReceptionist.setForeground(new java.awt.Color(255, 255, 255));
        lblRemoveReceptionist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemoveReceptionist.setText("Remove Receptionist");
        lblRemoveReceptionist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblRemoveReceptionist.setOpaque(true);
        lblRemoveReceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveReceptionistMouseClicked(evt);
            }
        });
        getContentPane().add(lblRemoveReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 220, 40));

        lblBack.setBackground(new java.awt.Color(0, 0, 0));
        lblBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Back");
        lblBack.setOpaque(true);
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 70, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 800, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddReceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceptionistMouseClicked
        RegisterReceptionistFrame addRecepFrame=new RegisterReceptionistFrame();
        addRecepFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAddReceptionistMouseClicked

    private void lblUpdateReceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateReceptionistMouseClicked
        UpdateReceptionistFrame updateRecepFrame=new UpdateReceptionistFrame();
        updateRecepFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblUpdateReceptionistMouseClicked

    private void lblViewReceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewReceptionistMouseClicked
        ViewReceptionistFrame view=new ViewReceptionistFrame();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblViewReceptionistMouseClicked

    private void lblRemoveReceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveReceptionistMouseClicked
        RemoveReceptionistFrame removeRecepFrame=new RemoveReceptionistFrame();
        removeRecepFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRemoveReceptionistMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        AdminOptionsFrame fr=new AdminOptionsFrame();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
//      int ans=JOptionPane.showConfirmDialog(null,"Are you sure?","Quitting",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//     if(ans==JOptionPane.YES_OPTION){
//         DBconnection.closeConnection();
//         System.exit(0);
//     } 
// TODO add your handling code here:
LoginFrame obj = new LoginFrame();
 obj.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReceptionistFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAddReceptionist;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRemoveReceptionist;
    private javax.swing.JLabel lblUpdateReceptionist;
    private javax.swing.JLabel lblViewReceptionist;
    // End of variables declaration//GEN-END:variables
}
