/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevni.gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import sanjeevni.dao.EmpDao;
import sanjeevni.dao.ReceptionistDao;
import sanjeevni.dao.UserDao;
import sanjeevni.dbutil.DBconnection;
import sanjeevni.pojo.ReceptionistPojo;
import sanjeevni.pojo.UserPojo;
import sanjeevni.utility.PasswordEncryption;

/**
 *
 * @author Admin
 */
public class RegisterReceptionistFrame extends javax.swing.JFrame {
    private String loginId,pwd,retypePwd,recepId,recepName;
    private Map<String,String> unRegRecepList = new HashMap<>();
    public RegisterReceptionistFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
        Image obj=tk.getImage("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Sanjeevni App\\src\\sanjeevni\\icons\\doctor.png");
        this.setIconImage(obj);
        loadRecepDetails();
        getNewRecepId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcEmpId = new javax.swing.JComboBox<>();
        txtReceptionistName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLoginId = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        txtRetypePwd = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcGender = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtReceptionistId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setText("Sanjeevni Application");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 450, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/icons/HomePageBG.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 280));

        btnRegister.setBackground(new java.awt.Color(0, 0, 0));
        btnRegister.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("REGISTER");
        btnRegister.setOpaque(true);
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 528, 180, 30));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("BACK");
        btnBack.setOpaque(true);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 568, 80, 30));

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setText("LOGOUT");
        btnLogout.setOpaque(true);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 568, 80, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/icons/images (2).jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 220, 250));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Employee ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jcEmpId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jcEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEmpIdActionPerformed(evt);
            }
        });
        jPanel1.add(jcEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 450, -1));

        txtReceptionistName.setEditable(false);
        txtReceptionistName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtReceptionistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 410, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Receptionist Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Login Id");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        txtLoginId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtLoginId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 450, -1));
        jPanel1.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 140, -1));
        jPanel1.add(txtRetypePwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 150, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Retype Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 140, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jcGender.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jcGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "NEUTRAL", " " }));
        jPanel1.add(jcGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 450, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Receptionist ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        txtReceptionistId.setEditable(false);
        txtReceptionistId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtReceptionistId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceptionistIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtReceptionistId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 440, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel18.setText("Add Receptionist ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 240, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 580, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEmpIdActionPerformed
    if(jcEmpId.getSelectedIndex()==-1)
        return;
     recepId=jcEmpId.getSelectedItem().toString();
     recepName=unRegRecepList.get(recepId);
     txtReceptionistName.setText(recepName);
    }//GEN-LAST:event_jcEmpIdActionPerformed

    private void txtReceptionistIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceptionistIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceptionistIdActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
       ManageReceptionistFrame aof=new  ManageReceptionistFrame();
       aof.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
    boolean validateInput=isValidInput();
      if(validateInput==false){
          JOptionPane.showMessageDialog(null,"Please input all the details!","ERROR",JOptionPane.ERROR_MESSAGE );
          return;
      }
       String passwordValid=matchPassword();
       if(passwordValid!=null){
           JOptionPane.showMessageDialog(null, passwordValid);
           return;
       }
     try{
         ReceptionistPojo recep=new ReceptionistPojo();
         recep.setGender(jcGender.getSelectedItem().toString());
         recep.setRecepId(txtReceptionistId.getText());
         recep.setRecepName(recepName);
         UserPojo user=new UserPojo();
         user.setUserId(loginId);
         user.setUserName(recepName);
         user.setUserType("RECEPTIONIST");
         String encPassword=PasswordEncryption.getEncryptedPassword(pwd);
         user.setPassword(encPassword);
         boolean result1=ReceptionistDao.addRecep(recep);
         boolean result2=UserDao.addUser(user);
           if(result1==true&&result2==true){
               JOptionPane.showMessageDialog(null,"Receptionist successfully registered!");
                clearAll();
                jcEmpId.removeItem(recepId);
               return;
           }
           JOptionPane.showMessageDialog(null,"Registration unsuccessfully!");
           clearAll();
           return;
       }
     catch(SQLException e){
         JOptionPane.showMessageDialog(null,"Error in DB!","ErrorInRegisterRecep",JOptionPane.ERROR_MESSAGE );
     }
     
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
// int ans=JOptionPane.showConfirmDialog(null,"Are you sure?","Quitting",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//     if(ans==JOptionPane.YES_OPTION){
//         DBconnection.closeConnection();
//         System.exit(0);
     //} 
     LoginFrame obj = new LoginFrame();
 obj.setVisible(true);
 this.dispose();
     // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterReceptionistFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcEmpId;
    private javax.swing.JComboBox<String> jcGender;
    private javax.swing.JTextField txtLoginId;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtReceptionistId;
    private javax.swing.JTextField txtReceptionistName;
    private javax.swing.JPasswordField txtRetypePwd;
    // End of variables declaration//GEN-END:variables

    private void loadRecepDetails() {
       try{
           unRegRecepList =EmpDao.getAllUnRegisteredRecep();
           Set<String> RecepId=unRegRecepList.keySet();
           if(RecepId==null){
               JOptionPane.showMessageDialog(null, "No Receptionist Present!");
               return;
           }
           for(String s:RecepId){
               jcEmpId.addItem(s);
           }
           
       }
         catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Error in DB "+e.getMessage(),"ERRORinRegisterRecep",JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
       }
    }
    
    private void getNewRecepId() {
        try{
        String recepId=ReceptionistDao.generateId();
        txtReceptionistId.setText(recepId);
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Error in DB "+e.getMessage(),"ERRORinRegisterRecep",JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
       }
        }
    private boolean isValidInput(){
        loginId=txtLoginId.getText();
       char[] p1=txtPwd.getPassword();
       char[] p2=txtPwd.getPassword();
       if(loginId==null||p1.length==0||p2.length==0){
           return false;
       }
       pwd=new String(p1);
       retypePwd=new String(p2);
       return true;
    }
    private String matchPassword(){
        if(pwd.length()<3||retypePwd.length()<3)
            return "Password length should be atleast 3 character in length";
        else if(!pwd.equals(retypePwd)){
            return "Password do not match";
        }
        return null;
    }

    private void clearAll() {
        try{
      txtLoginId.setText("");
      txtReceptionistName.setText("");
      txtPwd.setText("");
      txtRetypePwd.setText("");
      unRegRecepList.remove(recepId);
      txtReceptionistId.setText(ReceptionistDao.generateId());
      if(unRegRecepList.isEmpty()){
           JOptionPane.showMessageDialog(null, "ALL Receptionists registered successfully!");
             ManageReceptionistFrame fr=new ManageReceptionistFrame();
             fr.setVisible(true);
             this.dispose();
      } 
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error in DB!"+e.getMessage(),"ERRORinRegisterRecep",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
