/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevni.gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import sanjeevni.dao.DoctorDao;
import sanjeevni.dao.PatientDao;
import sanjeevni.dbutil.DBconnection;
import sanjeevni.pojo.PatientPojo;

/**
 *
 * @author Admin
 */
public class UpdatePatientFrame extends javax.swing.JFrame {
    private String contactNo,patId;
    private PatientPojo pat;
    public UpdatePatientFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();// this method give object of toolkit
        Image obj=tk.getImage("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Sanjeevni App\\src\\sanjeevni\\icons\\doctor.png");//remember the standard image getImage method take should be either in gif or jpg
        this.setIconImage(obj);
        loadDoctorId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOPD = new javax.swing.JTextField();
        jcPatientId = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcMstatus = new javax.swing.JComboBox<>();
        txtContactNo = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jcGender = new javax.swing.JComboBox<>();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jcDocId = new javax.swing.JComboBox<>();
        txtAge = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setText("Sanjeevni Application");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 450, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/icons/HomePageBG.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 280));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update Patients");
        jLabel5.setToolTipText("");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Doctor ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("OPD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 20));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Patient Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 20));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 20));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("City");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 100, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, 30));

        txtOPD.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtOPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 150, 30));

        jcPatientId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jcPatientId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcPatientIdItemStateChanged(evt);
            }
        });
        jcPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPatientIdActionPerformed(evt);
            }
        });
        jPanel1.add(jcPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 150, 30));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("First Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, 30));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Last Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, 30));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Gender");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Date");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Contact No");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, 30));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Marial Status");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, 30));

        jcMstatus.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jcMstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARRIED", "UNMARRIED" }));
        jPanel1.add(jcMstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, 30));

        txtContactNo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 130, 30));

        txtDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDate.setEnabled(false);
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 130, 30));

        jcGender.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jcGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "NEUTRAL", " " }));
        jPanel1.add(jcGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 130, 30));

        txtLastName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 130, 30));

        txtFirstName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 130, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate.setOpaque(true);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 110, 30));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.setOpaque(true);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 70, 30));

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogout.setOpaque(true);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 70, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 150, 50));

        jcDocId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jcDocId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDocIdItemStateChanged(evt);
            }
        });
        jcDocId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcDocIdMouseClicked(evt);
            }
        });
        jPanel1.add(jcDocId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 354, 150, 30));

        txtAge.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 150, 30));

        txtCity.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 150, 30));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jSeparator1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 780, 320));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/icons/images (2).jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 800, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPatientIdActionPerformed
   
    }//GEN-LAST:event_jcPatientIdActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
    if(validateInput()==false){
        JOptionPane.showMessageDialog(null,"Please fill all the details!");
        return;
    }
    try{
        pat.setPatientId(patId);
        boolean result=PatientDao.updatePatientDetails(pat);
        if(result==true){
           JOptionPane.showMessageDialog(null," Record updated successfully!","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
           return;
        }
        JOptionPane.showMessageDialog(null,"Recored not updated!","FAIL",JOptionPane.ERROR_MESSAGE);
        return;
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Error in DB!","ERRORinUpdatePat",JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
ReceptionistOptionsFrame fr=new ReceptionistOptionsFrame();
fr.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
// int ans=JOptionPane.showConfirmDialog(null,"Are you sure?","Quitting",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//     if(ans==JOptionPane.YES_OPTION){
//         DBconnection.closeConnection();
//         System.exit(0);
//     }        // TODO add your handling code here:
LoginFrame obj = new LoginFrame();
 obj.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void jcDocIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcDocIdMouseClicked
      
    }//GEN-LAST:event_jcDocIdMouseClicked

    private void jcDocIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDocIdItemStateChanged
       String docId=jcDocId.getSelectedItem().toString();
       loadPatientId(docId);
    }//GEN-LAST:event_jcDocIdItemStateChanged

    private void jcPatientIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcPatientIdItemStateChanged
        try{
         patId=jcPatientId.getSelectedItem().toString();
         pat=PatientDao.getPatientDetailByPatientId(patId);
         txtCity.setText(pat.getCity());
         txtAge.setText(pat.getAge()+"");
         txtAddress.setText(pat.getAddress());
         txtOPD.setText(pat.getOpd());
         txtFirstName.setText(pat.getFirstName());
         txtLastName.setText(pat.getLastName());
         jcGender.setSelectedItem(pat.getGender());
    //     txtDate.setText(pat.getpDate());
         txtContactNo.setText(pat.getMobileNo());
         jcMstatus.setSelectedItem(pat.getmStatus());
     }
         catch(SQLException e){
          JOptionPane.showMessageDialog(null,"Error in DB!","ERRORinUpdatePat",JOptionPane.ERROR_MESSAGE);
          e.printStackTrace();
      }
    }//GEN-LAST:event_jcPatientIdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcDocId;
    private javax.swing.JComboBox<String> jcGender;
    private javax.swing.JComboBox<String> jcMstatus;
    private javax.swing.JComboBox<String> jcPatientId;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOPD;
    // End of variables declaration//GEN-END:variables

    private void loadPatientId(String docId) {
      try{
          List<String>patIdList=PatientDao.getPatIdByDocId(docId);
          if(patIdList==null){
               JOptionPane.showMessageDialog(null,"No patient Present!");
               return;
          }
          for(String patId:patIdList){
              jcPatientId.addItem(patId);
              System.out.println(patId);
          }
      }
      catch(SQLException e){
          JOptionPane.showMessageDialog(null,"Error in DB!","ERRORinUpdatePat",JOptionPane.ERROR_MESSAGE);
          e.printStackTrace();
      }
    }

    private void loadDoctorId() {
        try{
   List<String>docIdList=DoctorDao.getAllDoctorId();
   if(docIdList==null){
               JOptionPane.showMessageDialog(null,"No Doctor Present!");
               return;
          }
          for(String docId:docIdList){
              jcDocId.addItem(docId);
          }
    }
        catch(SQLException e){
          JOptionPane.showMessageDialog(null,"Error in DB!","ERRORinUpdatePat",JOptionPane.ERROR_MESSAGE);
          e.printStackTrace();
      }  
    }
      private boolean isContactValid(){
        contactNo=txtContactNo.getText();
        char []mob=contactNo.toCharArray();
        for(char ch:mob){
            if(Character.isDigit(ch)==false){
                return false;
            }
        }
        if(contactNo.length()==10){
            return true;
        }
        return false;
    }
    private boolean validateInput(){
        pat.setCity(txtCity.getText());
        pat.setFirstName(txtFirstName.getText());
        pat.setLastName(txtLastName.getText());
       // pat.setpDate(dt);
        pat.setGender(jcGender.getSelectedItem().toString());
        pat.setAddress(txtAddress.getText().trim());
        pat.setMobileNo(txtContactNo.getText().trim());
        pat.setmStatus(jcMstatus.getSelectedItem().toString());
        pat.setOpd(txtOPD.getText());
       if(txtFirstName.getText().isEmpty()||txtLastName.getText().isEmpty()||txtContactNo.getText().isEmpty()||txtCity.getText().isEmpty()||txtAddress.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Please fill the details!");
           return false;  
        }
        try{
              pat.setAge(Integer.parseInt(txtAge.getText().trim()));
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null,"Invalid Age"+e);
          return false;
       }
       
        if(isContactValid()==false){
            JOptionPane.showMessageDialog(null,"Invalid PhoneNo.");
            return false;
        }
        return true;  
    }
}
