/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevni.gui;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sanjeevni.dao.AppointmentDao;
import sanjeevni.dao.DoctorDao;
import sanjeevni.dao.PatientDao;
import sanjeevni.pojo.AppointmentPojo;
import sanjeevni.pojo.PatientPojo;
import sanjeevni.utility.OtpSender;
import sanjeevni.utility.Sender;

public class VerifyOtpScreen extends javax.swing.JFrame {

    /**
     * Creates new form VerifyOtpScreen
     */
    private static PatientPojo patient;
    public VerifyOtpScreen() {
        initComponents();
        setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
        Image img=tk.getImage("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Sanjeevni App\\src\\sanjeevni\\icons\\doctor.png");
        this.setIconImage(img);
        
    }
    public VerifyOtpScreen(PatientPojo pat){
        this();// concept of constructor cascading
        txtPatName.setText(pat.getFirstName()+" "+pat.getLastName());
        txtContactNo.setText(pat.getMobileNo());
        this.patient=pat;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPatName = new javax.swing.JTextField();
        lblVerify = new javax.swing.JLabel();
        btnQuit = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSendOtp = new javax.swing.JLabel();
        txtOTP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel6.setText("Sanjeevni Application");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 450, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/icons/HomePageBG1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, -1, 410));

        txtPatName.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        txtPatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtPatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 210, 30));

        lblVerify.setBackground(new java.awt.Color(0, 0, 0));
        lblVerify.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        lblVerify.setForeground(new java.awt.Color(255, 255, 255));
        lblVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerify.setText("VERIFY");
        lblVerify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblVerify.setOpaque(true);
        lblVerify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerifyMouseClicked(evt);
            }
        });
        getContentPane().add(lblVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 200, 30));

        btnQuit.setBackground(new java.awt.Color(0, 0, 0));
        btnQuit.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuit.setText("BACK");
        btnQuit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnQuit.setOpaque(true);
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        getContentPane().add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 110, 30));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("LOGOUT");
        lblLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 120, 30));

        txtContactNo.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 220, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel8.setText("Enter OTP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 90, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel4.setText("Patient Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 100, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel5.setText("Phone No.");
        jLabel5.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel5ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 110, -1));

        lblSendOtp.setBackground(new java.awt.Color(0, 0, 0));
        lblSendOtp.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        lblSendOtp.setForeground(new java.awt.Color(255, 255, 255));
        lblSendOtp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSendOtp.setText("SEND OTP");
        lblSendOtp.setOpaque(true);
        lblSendOtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSendOtpMouseClicked(evt);
            }
        });
        getContentPane().add(lblSendOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 350, 30));
        getContentPane().add(txtOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 210, 30));

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 790, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatNameActionPerformed

    private void lblVerifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerifyMouseClicked
     if(isValidOtp()==false){
       JOptionPane.showMessageDialog(null,"Invalid OTP ,Try Again! ","Error",JOptionPane.ERROR_MESSAGE);  
       return;
     }
     try
     {
         AppointmentPojo appojo=new AppointmentPojo();
         appojo.setDateTime(patient.getpDate().toString());
         appojo.setMobileNo(patient.getMobileNo());
         appojo.setPatientId(patient.getPatientId());
         appojo.setPatientName(txtPatName.getText().trim());
         appojo.setStatus("REQUEST");
         appojo.setOpd(patient.getOpd().trim());
         appojo.setDoctorName(DoctorDao.getDoctorNameById(patient.getDoctorId()));
         boolean result1= PatientDao.addPatients(patient);
         boolean result2=AppointmentDao.addAppointment(appojo);
         if(result1==result2){
             JOptionPane.showMessageDialog(null,"Patient record saved!");   
             ViewAllPatientFrame vpf=new ViewAllPatientFrame();
             vpf.setVisible(true);
             this.dispose();
         }
         else{
             JOptionPane.showMessageDialog(null, "Sorry! could not add the patient record");
             return;
         }
     }
     catch(SQLException e){
       JOptionPane.showMessageDialog(null, "Error in DB!");
       e.printStackTrace();
       
     }
     
    }//GEN-LAST:event_lblVerifyMouseClicked

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
      AddPatientFrame apf=new AddPatientFrame();
      apf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnQuitMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
// int ans=JOptionPane.showConfirmDialog(null,"Are you sure?","Quitting",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//     if(ans==JOptionPane.YES_OPTION){
//         DBconnection.closeConnection();
//         System.exit(0);
//     }        // TODO add your handling code here:
LoginFrame obj = new LoginFrame();
 obj.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void jLabel5ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel5ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5ComponentAdded

    private void lblSendOtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSendOtpMouseClicked
        try{
            Sender sendObj=new OtpSender();
            String pOtp=String.valueOf(patient.getOtp());
            
            boolean result=sendObj.send(patient.getMobileNo(),pOtp);
            if(result==false){
                JOptionPane.showMessageDialog(null, "OTP could not be send,Please!check the no.","FAILURE",JOptionPane.ERROR_MESSAGE);//dnd activated or no is wrong
//               try{
//                   boolean ans=checkPhoneNo(txtContactNo.getText().trim());
//                   if(ans==false){
//                      JOptionPane.showMessageDialog(null, "Wrong Number!","FAILURE",JOptionPane.ERROR_MESSAGE); 
//                      return;
//                   }
//               pat.setMobileNo(txtContactNo.getText().trim());
//                   
//               }
//               catch(SQLException e){
//                   JOptionPane.showMessageDialog(null,"Error in db!");
//                   return;
//               }
            }
            else{
                JOptionPane.showMessageDialog(null,"OTP sent successfully!");
            }   
            
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"Server issues! "+e.getMessage());//network or connection problem
             e.printStackTrace();
        }
    }//GEN-LAST:event_lblSendOtpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerifyOtpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblSendOtp;
    private javax.swing.JLabel lblVerify;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JTextField txtPatName;
    // End of variables declaration//GEN-END:variables
private boolean isValidOtp(){
    boolean result=false;
    try{
        int otp=Integer.parseInt(txtOTP.getText().trim());
        if(otp==patient.getOtp()){
           result=true;
        }  
    }
    catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,"Please Enter numeric values!");  
    }
    finally{
    return result;
    }
}
    private boolean checkPhoneNo(String No){
        if(No.length()!=10)
            return false;
        for(int i=0;i<No.length();i++){
            if(No.charAt(i)<47||No.charAt(i)>58)
                return false;
        }
        return true;
    } 
}
